import { DefaultTheme } from "styled-components";

export const LightTheme: DefaultTheme = {
  borderRadius: "5px",

  colors: {
    mainBackground: "#F2F2F2",
    menuBackground: "#1E2139",
    invoiceDetailBackground: "#fff",
    invoiceTotalBackground: "#0C0E16",
    invoiceItemBackground: "#F9FAFE",
    userOptionBackground: "#fff",
    editFormBackground: "#fff",
    inputFieldBackground: "#fff",
    backgroundColorLight: "#F9FAFE",
    borderColorLight: "#DFE3FA",
    mainFontColor: "#0C0E16",
    textColorLight: "#858BB2",
    textColorLight2: "#888EB0",
    statusPaid: "#33D69F",
    statusPaidBackground: "rgba(51, 214, 159, 0.1)",
    statusPending: "#FF8F00",
    statusPendingBackground: "rgba(255, 143, 0, 0.1)",
    statusDraft: "#373B53",
    statusDraftBackground: "rgba(55, 59, 83, 0.1)",
    warnButton: "#EC5757",
    warnButtonHover: "#FF9797",
    secondaryButton: "#7E88C3",
    secondaryButtonBackground: "#F9FAFE",
    secondaryButtonHover: "#DFE3FA",
    darkPurple: "#7C5DFA",
    lightPurple: "#9277FF",
    secondary: "magenta",
  },
};

export const DarkTheme: DefaultTheme = {
  borderRadius: "5px",

  colors: {
    mainBackground: "#0C0E16",
    menuBackground: "#1E2139",
    invoiceDetailBackground: "#1E2139",
    invoiceTotalBackground: "#0C0E16",
    editFormBackground: "#141625",
    inputFieldBackground: "#1E2139",
    invoiceItemBackground: "#252945",
    userOptionBackground: "#1E2139",
    backgroundColorLight: "#979797",
    borderColorLight: "#252945",
    mainFontColor: "#FFFFFF",
    textColorLight: "#DFE3FA",
    textColorLight2: "#888EB0",
    statusPaid: "#33D69F",
    statusPaidBackground: "rgba(51, 214, 159, 0.1)",
    statusPending: "#FF8F00",
    statusPendingBackground: "rgba(255, 143, 0, 0.1)",
    statusDraft: "#373B53",
    statusDraftBackground: "rgba(55, 59, 83, 0.1)",
    warnButton: "#EC5757",
    warnButtonHover: "#FF9797",
    secondaryButton: "#DFE3FA",
    secondaryButtonBackground: "#252945",
    secondaryButtonHover: "#FFFFFF",
    darkPurple: "#7C5DFA",
    lightPurple: "#9277FF",
    secondary: "magenta",
  },
};
